version: "3"

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
volumes:
  mysql_volume:
